ALTER TABLE users
    ADD COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST ,
ADD PRIMARY KEY (id), ADD UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE;

ALTER TABLE events
    ADD COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (id),
ADD UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE;
