ALTER TABLE users
    ADD COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST ,
ADD PRIMARY KEY (id), ADD UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE;

ALTER TABLE events
    CHANGE COLUMN id id VARCHAR(200) NOT NULL ,
    ADD PRIMARY KEY (id),
    ADD UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE;